name: Render Remotion Video

on:
  repository_dispatch:
    types: [render-video]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Render Video with Remotion
        env:
          VIDEO_URLS: ${{ toJson(github.event.client_payload.videoUrls) }}
          AUDIO_URL: ${{ github.event.client_payload.audioUrl }}
          IMAGES: ${{ toJson(github.event.client_payload.images) }}
          DURATION: ${{ github.event.client_payload.duration }}
          IMAGE_DURATION: ${{ github.event.client_payload.imageDuration }}
          SUBTITLES: ${{ toJson(github.event.client_payload.subtitles) }}
          SUBTITLE_STYLE: ${{ github.event.client_payload.styleType }}
          AUDIO_VOLUME: ${{ github.event.client_payload.audioVolume }}
        run: |
          echo "Rendering video with props:"
          echo "Video URLs: $VIDEO_URLS"
          echo "Audio URL: $AUDIO_URL"
          echo "Duration: $DURATION"
          echo "Audio Volume: $AUDIO_VOLUME"
          echo "Images: $IMAGES"
          echo "Subtitles: $SUBTITLES"
          echo "Subtitle Style: $SUBTITLE_STYLE"
          
          # Build props JSON conditionally
          PROPS="{\"videoUrls\": $VIDEO_URLS, \"audioUrl\": \"$AUDIO_URL\", \"audioVolume\": $AUDIO_VOLUME, \"images\": $IMAGES, \"subtitles\": $SUBTILES, \"styleType\": \"$SUBTITLE_STYLE\", \"duration\": $DURATION}"
          
          # Only include imageDuration if it exists
          if [ ! -z "$IMAGE_DURATION" ]; then
            PROPS=$(echo $PROPS | jq ". + {\"imageDuration\": $IMAGE_DURATION}")
          fi
          
          npx remotion render VideoWithSubtitles \
            --props="$PROPS" \
            --output="rendered-video.mp4"

      - name: Upload Rendered Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video
          path: "*.mp4"
          retention-days: 7
