name: Render Remotion Video

on:
  repository_dispatch:
    types: [render-video]

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Render Video with Remotion
        env:
          VIDEO_URLS: ${{ toJson(github.event.client_payload.videoUrls) }}
          AUDIO_URL: ${{ github.event.client_payload.audioUrl }}
          IMAGES: ${{ toJson(github.event.client_payload.images) }}
          DURATION: ${{ github.event.client_payload.duration }}
          IMAGE_DURATION: ${{ github.event.client_payload.imageDuration }}
          SUBTITLES: ${{ toJson(github.event.client_payload.subtitles) }}
          SUBTITLE_STYLE: ${{ github.event.client_payload.styleType }}
          AUDIO_VOLUME: ${{ github.event.client_payload.audioVolume }}
          OUTPUT_FILE: ${{ github.event.client_payload.outputFile }}
          UNIQUE_ID: ${{ github.event.client_payload.uniqueId }}
        run: |
          echo "Rendering video with props:"
          echo "Unique ID: $UNIQUE_ID"
          echo "Video URLs: $VIDEO_URLS"
          echo "Audio URL: $AUDIO_URL"
          echo "Duration: $DURATION"
          echo "Audio Volume: $AUDIO_VOLUME"
          echo "Images: $IMAGES"
          echo "Subtitles: $SUBTITLES"
          echo "Subtitle Style: $SUBTITLE_STYLE"
          echo "Output File: $OUTPUT_FILE"

          # Build props JSON
          PROPS=$(jq -n \
            --argjson videoUrls "$VIDEO_URLS" \
            --arg audioUrl "$AUDIO_URL" \
            --argjson audioVolume "$AUDIO_VOLUME" \
            --argjson images "$IMAGES" \
            --argjson subtitles "$SUBTITLES" \
            --arg styleType "$SUBTITLE_STYLE" \
            --argjson duration "$DURATION" \
            --arg uniqueId "$UNIQUE_ID" \
            '{
              videoUrls: $videoUrls,
              audioUrl: $audioUrl,
              audioVolume: $audioVolume,
              images: $images,
              subtitles: $subtitles,
              styleType: $styleType,
              duration: $duration,
              uniqueId: $uniqueId
            }')

          if [ ! -z "$IMAGE_DURATION" ]; then
            PROPS=$(echo $PROPS | jq --argjson imageDuration "$IMAGE_DURATION" '. + {imageDuration: $imageDuration}')
          fi

          echo "Constructed PROPS: $PROPS"

          npx remotion render VideoWithSubtitles \
            --props="$PROPS" \
            --output="$OUTPUT_FILE"

      - name: Upload Rendered Video as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rendered-video-${{ github.event.client_payload.uniqueId }}
          path: "${{ github.event.client_payload.outputFile }}"
          retention-days: 7
